name: Sub workflow 3 Production

on:
  workflow_call:
  workflow_run:
    workflows: [Sub workflow 3 Staging]
    types:
      - completed

jobs:
  approve-prod:
    if: ${{ github.event.workflow_run.conclusion == null || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 5
        with:
          secret: ${{ github.token }}
          approvers: songwongtp
          minimum-approvals: 1
          issue-title: "Test sub3"
          exclude-workflow-initiator-as-approver: false
  execute:
    needs: [approve-prod]
    runs-on: ubuntu-latest
    steps:
      - name: apply
        run: echo "Sub3 Production"
